### ISSUE TITLE
homepage background reverts to white on restart

### ISSUE THREAD

**Issue by ak1dd** [andreicristianpetcu/firefox_themes#1]
first,  thanks for this theme - using the dark version.   I saw it on reddit and jumped at it.   When I first install it, or activate it - all the homepage and configuration backgrounds are dark (which is the main reason I was eager to try your extension).    Upon restart they all revert to white.   Is this something that can be addressed?  Or am I missing something.

**Comment by andreicristianpetcu** [comment]
Please share a screenshot @ak1dd 
Not sure I understand. What ff version?

**Comment by ak1dd** [comment]
Sorry, I just figured it out.   I had the FF Color extension installed.   When I removed it all worked correctly.   Not sure why that extension does that but...
