### ISSUE TITLE
No highlighting in search box

### ISSUE THREAD

**Issue by Iruberiam** [andreicristianpetcu/firefox_themes#2]
Text typed into the search box can't be highlighted.
This is with all versions.

**Comment by andreicristianpetcu** [comment]
please share a screenshot @Iruberiam

**Comment by Iruberiam** [comment]
Hi, here's a screenshot.
![image](https://user-images.githubusercontent.com/25612005/73135639-48187800-403c-11ea-8301-aac07724fce6.png)

**Comment by andreicristianpetcu** [comment]
Can you please try to uninstall and reinstall the theme? You might be on an old version. This is how it looks on my browser
![image](https://user-images.githubusercontent.com/922368/73138516-18816400-406c-11ea-9737-38839fd48622.png)

**Comment by andreicristianpetcu** [comment]
Hmmmmm. This looks better 
![image](https://user-images.githubusercontent.com/922368/73138575-c260f080-406c-11ea-879b-4d0f611ded02.png)

**Comment by andreicristianpetcu** [comment]
I fixed this in v1.11. It will look like in the above image.

**Comment by Iruberiam** [comment]
Oh yes, this is great thanks for your fast response.
